댓글 CRUD API
devarium/devarium-backend pull request #2
Opened 2024-12-10 03:52 UTC by a-white-bit

2024-12-12 06:07 UTC, sillysillyman commented on infrastructure/src/main/java/io/devarium/infrastructure/persistence/repository/CommentRepositoryImpl.java
> +    }
이 메서드에 오류가 있어서 수정이 필요할 것 같습니다. BE-8 브랜치의 `PostRepositoryImpl`을 참고해주세요. 이 메서드는 도메인 모델을 엔티티로 변환하는 것인데, 그 변환 방법이 객체를 생성하는 것입니다. 이 때 `save` 메서드가 수정할 때 사용된다면 기존 엔티티의 `createdAt`, `updatedAt`이 `null`이 되는 오류가 발생합니다. 따라서 `domain.getId()`가 `null`이 아닌 경우는 기존 엔티티가 존재한다는 것이므로 `commentJpaRepository`에서 해당 엔티티를 가져와서 처리해야 합니다.

2024-12-12 06:07 UTC, sillysillyman commented on infrastructure/src/main/java/io/devarium/infrastructure/persistence/entity/CommentEntity.java
> +    private String content;
`@Column(nullable = false)` 제약 조건을 추가해주세요.

2024-12-15 16:09 UTC, sillysillyman reviewed
테스트 코드에서 예외가 잘 발생하는지 확인하는 경우에 메시지 동등성 검사는 하지 않으셔도 됩니다. 추후에 메시지가 변경될 때 불필요하게 테스트 코드의 메시지도 변경해야 하는 단점이 있습니다. 그냥 예외 종류만 검사해주세요!

2024-12-26 03:54 UTC, sillysillyman requested changes

2024-12-26 03:54 UTC, sillysillyman commented on infrastructure/src/main/java/io/devarium/infrastructure/persistence/repository/CommentRepositoryImpl.java
>  public class CommentRepositoryImpl implements CommentRepository {
Repository는 자신의 엔티티 대한 영속성 관리만 담당해야 하는데 현재는 Comment가 Post와 Reply의 생명주기까지 관리하고 있습니다. Service 계층에서 다른 도메인의 생명주기를 관리하는 게 좋을 것 같습니다.

2024-12-26 04:02 UTC, sillysillyman commented on api/src/main/java/io/devarium/api/controller/comment/CommentController.java
> +    @GetMapping("/all/{postId}")
이건 `PostController`에서 GET "/posts/{postId}/comments" 호출하는 게 RESTful 해보이기는 합니다.

2024-12-26 07:07 UTC, sillysillyman commented on infrastructure/src/main/java/io/devarium/infrastructure/persistence/service/ReplyServiceDecorator.java
> +    public void deleteRepliesByPostId(Long postId) {
이 메서드의 역할이 무엇인가요?

2024-12-26 07:35 UTC, sillysillyman approved these changes
convertToEntity 때문에 Repository에서 다른 엔티티 Repository를 주입 받는 게 좀 걸리긴 해서 해결방안 생각해볼게요. 일단은 승인하겠습니다.

2024-12-26 09:53 UTC, onda0-0 approved these changes

2024-12-26 10:16 UTC, merged